{"name": "Переход на вкладку Оплата. Страхователь является застрахованным. Страховая сумма 100000", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных", "trace": "self = <selene.core.wait.Wait object at 0x0000022AD6BE5660>, fn = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\n\n    def for_(self, fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self._entity)\n\nentity     = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\nfailure    = TimeoutException(\"\\n\\nTimed out after 4s, while waiting for:\\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\\n\\nReason: AssertionError: actual text: 2. Ввод данных\")\nfinish_time = 1666593134.5324621\nfn         = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\nreason_message = 'actual text: 2. Ввод данных'\nreason_string = 'AssertionError: actual text: 2. Ввод данных'\nself       = <selene.core.wait.Wait object at 0x0000022AD6BE5660>\ntimeout    = 4\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py:102: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>, entity = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\n\n    def __call__(self, entity: E) -> None:\n>       return self._fn(entity)\n\nentity     = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\nself       = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\condition.py:151: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nentity = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\n\n    def fn(entity: E) -> None:\n        query_to_str = str(query)\n        result = (\n            query.__name__\n            if query_to_str.startswith('<function')\n            else query_to_str\n        )\n        actual = query(entity)\n        if not predicate(actual):\n>           raise AssertionError(f'actual {result}: {actual}')\nE           AssertionError: actual text: 2. Ввод данных\n\nactual     = '2. Ввод данных'\nentity     = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\npredicate  = <function includes.<locals>.fn at 0x0000022AD6C103A0>\nquery      = <selene.core.wait.Query object at 0x0000022AD5B4D150>\nquery_to_str = 'text'\nresult     = 'text'\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\condition.py:124: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.ui.test_form_data.TestCalculateForm object at 0x0000022AD6858D00>\nopen_policy_purchase_form_go_to_data_tab = <function open_policy_purchase_form_go_to_data_tab.<locals>._open at 0x0000022AD6C11AB0>\n\n    @allure.title('Переход на вкладку Оплата. Страхователь является застрахованным. Страховая сумма 100000')\n    def test_open_payment_form_change_sum(self, open_policy_purchase_form_go_to_data_tab):\n        test_data = FormDataBuilder().random_with_add_person().build()\n    \n        policy_form_page = open_policy_purchase_form_go_to_data_tab(change_sum=True)\n        policy_form_page.fill_form_data(test_data)\n        policy_form_page.click_on_go_to_payments_tab()\n>       policy_form_page.assure_current_step_name(StepNameData.STEP_PAYMENT)\n\nopen_policy_purchase_form_go_to_data_tab = <function open_policy_purchase_form_go_to_data_tab.<locals>._open at 0x0000022AD6C11AB0>\npolicy_form_page = <core.pages.coronavirus_insurance_policy_page.CoronavirusInsurancePolicyPage object at 0x0000022AD6BE6B90>\nself       = <tests.ui.test_form_data.TestCalculateForm object at 0x0000022AD6858D00>\ntest_data  = FormData(fio='Сафонов Ратмир Димитриевич', birthday='04.08.1998', doc_data='8763-852428', doc_issue_date='13.04.2011',...'stepan2007@rao.ru', add_person=True, name_insured=None, date_birth_insured=None, id_insured=None, id_dateInsured=None)\n\ntests\\ui\\test_form_data.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncore\\pages\\coronavirus_insurance_policy_page.py:80: in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n        self       = <core.pages.coronavirus_insurance_policy_page.CoronavirusInsurancePolicyPage object at 0x0000022AD6BE6B90>\n        value      = <StepNameData.STEP_PAYMENT: '3. Оплата'>\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py:539: in should\n    super().should(condition)\n        __class__  = <class 'selene.core.entity.Element'>\n        condition  = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\n        self       = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\n        timeout    = None\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py:126: in should\n    self.wait.for_(condition)\n        condition  = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\n        self       = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.wait.Wait object at 0x0000022AD6BE5660>, fn = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\n\n        def for_(self, fn: Callable[[E], R]) -> R:\n            finish_time = time.time() + self._timeout\n    \n            while True:\n                try:\n                    return fn(self._entity)\n                except Exception as reason:\n                    if time.time() > finish_time:\n    \n                        reason_message = str(reason)\n    \n                        reason_string = '{name}: {message}'.format(\n                            name=reason.__class__.__name__, message=reason_message\n                        )\n                        # todo: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                        # stacktrace = getattr(reason, 'stacktrace', None)\n                        timeout = self._timeout\n                        entity = self._entity\n    \n                        failure = TimeoutException(\n                            f'''\n    \n    Timed out after {timeout}s, while waiting for:\n    {entity}.{fn}\n    \n    Reason: {reason_string}'''\n                        )\n    \n>                       raise self._hook_failure(failure)\nE                       selene.core.exceptions.TimeoutException: Message: \nE                       \nE                       Timed out after 4s, while waiting for:\nE                       browser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\nE                       \nE                       Reason: AssertionError: actual text: 2. Ввод данных\n\nentity     = <selene.core.entity.Element object at 0x0000022AD6BE7DF0>\nfailure    = TimeoutException(\"\\n\\nTimed out after 4s, while waiting for:\\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\\n\\nReason: AssertionError: actual text: 2. Ввод данных\")\nfinish_time = 1666593134.5324621\nfn         = <selene.core.conditions.ElementCondition object at 0x0000022AD6BE5BA0>\nreason_message = 'actual text: 2. Ввод данных'\nreason_string = 'AssertionError: actual text: 2. Ввод данных'\nself       = <selene.core.wait.Wait object at 0x0000022AD6BE5660>\ntimeout    = 4\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py:125: TimeoutException"}, "steps": [{"name": "Переход по адресу: \"https://old.absolutins.ru/kupit-strahovoj-polis/strahovanie-zhizni-i-zdorovya/zashchita-ot-virusa/\"", "status": "passed", "start": 1666593120347, "stop": 1666593124908}, {"name": "Выбрать страховую сумму полиса.", "status": "passed", "steps": [{"name": "выбрать сумму: 100000", "status": "passed", "start": 1666593124908, "stop": 1666593126206}], "parameters": [{"name": "sum_value", "value": "100000"}], "start": 1666593124908, "stop": 1666593126206}, {"name": "Выбрать чекбокс \"Подтверждаю, что -  Отсутствуют лица, проживающие совместно с Застрахованным, у которых диагностирована коронавирусная инфекция COVID-2019 ( код заболевания по МКБ-10 – В 34.2.)\".", "status": "passed", "start": 1666593126206, "stop": 1666593127140}, {"name": "Нажать кнопку \"Продолжить\".", "status": "passed", "start": 1666593127141, "stop": 1666593127824}, {"name": "Заполнить форму \"Ввод данных\"", "status": "passed", "steps": [{"name": "Заполнить поле \"ФИО страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: Сафонов Ратмир Димитриевич", "status": "passed", "start": 1666593127825, "stop": 1666593128450}], "parameters": [{"name": "value", "value": "'Сафонов Ратмир Димитриевич'"}], "start": 1666593127824, "stop": 1666593128450}, {"name": "Заполнить поле \"Дата рождения страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: 04.08.1998", "status": "passed", "start": 1666593128451, "stop": 1666593128510}], "parameters": [{"name": "value", "value": "'04.08.1998'"}], "start": 1666593128451, "stop": 1666593128510}, {"name": "Заполнить поле \"Серия/номер паспорта страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: 8763-852428", "status": "passed", "start": 1666593128510, "stop": 1666593128606}], "parameters": [{"name": "value", "value": "'8763-852428'"}], "start": 1666593128510, "stop": 1666593128606}, {"name": "Заполнить поле \"Дата выдачи\"", "status": "passed", "steps": [{"name": "Ввести значение: 13.04.2011", "status": "passed", "start": 1666593128606, "stop": 1666593128675}], "parameters": [{"name": "value", "value": "'13.04.2011'"}], "start": 1666593128606, "stop": 1666593128675}, {"name": "Заполнить поле \"Адрес регистрации\"", "status": "passed", "steps": [{"name": "Ввести значение: к. Бодайбо, ш. Народное, д. 6 к. 280, 634420", "status": "passed", "start": 1666593128675, "stop": 1666593129322}], "parameters": [{"name": "value", "value": "'к. Бодайбо, ш. Народное, д. 6 к. 280, 634420'"}], "start": 1666593128675, "stop": 1666593129322}, {"name": "Заполнить поле \"Телефон\"", "status": "passed", "steps": [{"name": "Ввести значение: +7(461)-647-88-87", "status": "passed", "start": 1666593129323, "stop": 1666593129623}], "parameters": [{"name": "value", "value": "'+7(461)-647-88-87'"}], "start": 1666593129323, "stop": 1666593129623}, {"name": "Заполнить поле \"Email\"", "status": "passed", "steps": [{"name": "Ввести значение: stepan2007@rao.ru", "status": "passed", "start": 1666593129623, "stop": 1666593129915}], "parameters": [{"name": "value", "value": "'stepan2007@rao.ru'"}], "start": 1666593129623, "stop": 1666593129915}], "parameters": [{"name": "value", "value": "FormData(fio='Сафонов Ратмир Димитриевич', birthday='04.08.1998', doc_data='8763-852428', doc_issue_date='13.04.2011', registration_address='к. Бодайбо, ш. Народное, д. 6 к. 280, 634420', phone='+7(461)-647-88-87', email='stepan2007@rao.ru', add_person=True, name_insured=None, date_birth_insured=None, id_insured=None, id_dateInsured=None)"}], "start": 1666593127824, "stop": 1666593129915}, {"name": "Нажать кнопку \"Перейти к оплате\"", "status": "passed", "steps": [{"name": "Ожидание прогрузки страницы", "status": "passed", "start": 1666593130157, "stop": 1666593130507}], "start": 1666593129915, "stop": 1666593130507}, {"name": "Проверить название текущего шага.", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных\n\n", "trace": "  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\alpik\\PycharmProjects\\absolutins\\core\\pages\\coronavirus_insurance_policy_page.py\", line 80, in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 539, in should\n    super().should(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 126, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "Скролл к началу страницы", "status": "passed", "start": 1666593130508, "stop": 1666593130532}, {"name": "Текущий активный шаг: 3. Оплата", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных\n\n", "trace": "  File \"C:\\Users\\alpik\\PycharmProjects\\absolutins\\core\\pages\\coronavirus_insurance_policy_page.py\", line 80, in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 539, in should\n    super().should(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 126, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "start": 1666593130532, "stop": 1666593134540}], "parameters": [{"name": "value", "value": "'3. Оплата'"}], "start": 1666593130507, "stop": 1666593134541}], "attachments": [{"name": "failure-screenshot", "source": "81babe5e-a457-4c25-8969-9d715c58d9d7-attachment.png", "type": "image/png"}, {"name": "js-console-log", "source": "48c6e35e-7b30-4173-9ae0-2bad7936d8b7-attachment.txt", "type": "text/plain"}, {"name": "driver-log", "source": "02bcd7dc-1988-4b32-b6e9-a5eeceae8ac0-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "2a488fa3-8c58-4c7b-b560-2bfedc08f247-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ef35702e-ff1d-4449-a87e-be5f8330ba56-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "455d71bf-630b-4923-8462-636cc99e4b8f-attachment.txt", "type": "text/plain"}], "start": 1666593120143, "stop": 1666593134542, "uuid": "11f34d73-3f71-4cd0-b3b8-ca7c82398dfa", "historyId": "a38683bf2f127fb42cec6d5a7d23834c", "testCaseId": "196a6ea48631f0dae90a4e7e34b422ed", "fullName": "ui.test_form_data.TestCalculateForm#test_open_payment_form_change_sum", "labels": [{"name": "subSuite", "value": "Ввод данных"}, {"name": "suite", "value": "Форма покупки полиса"}, {"name": "parentSuite", "value": "Регрессионное тестирование"}, {"name": "tag", "value": "regress"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_browser')"}, {"name": "host", "value": "DESKTOP-GMLT5VV"}, {"name": "thread", "value": "22688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ui.test_form_data"}]}